### ISSUE TITLE
 报错：BaiduNaviManager.getInstance().init(cordova.getActivity(), mSDCardPath, null, new BaiduNaviManager.NaviInitListener() 

### ISSUE THREAD

**Issue by www-okrs-cn** [huangliop/cordova-baidu-navigator#1]
你好，我在编译的时候出现了如下问题：
postalApp\platforms\android\src\cn\baidu\navigator\Navigator.java:44: ����: �޷����� BaiduNaviManager�еķ��� initӦ�õ���������;
        BaiduNaviManager.getInstance().init(cordova.getActivity(), mSDCardPath, null, new BaiduNaviManager.NaviInitListener() {
                                      ^
  ��Ҫ: Activity,String,String,NaviInitListener,BNOuterTTSPlayerCallback
  �ҵ�: Activity,String,<��ֵ>,<����NaviInitListener>,<��ֵ>,MyHandler,<��ֵ>
  ԭ��: ʵ�ʲ����б�����ʽ�����б����Ȳ�ͬ
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by huangliop** [comment]
tts 的问题，已经解决
